module.exports = [
    {
        title: "Off with Their Heads!",
        author: "Antony Taylor",
        profession: "",
        date: "2021-06-15",
        image: "https://www.historytoday.com/sites/default/files/inline-images/BTT%20full%20size.jpg",
        para : "Recent years have seen a slow but steadily rising tide of dissatisfaction with royalty in Britain. Accelerated by the death of Queen Elizabeth II, the coronation of King Charles III and a regular diet of scandal surrounding Prince Andrew, as well as the fracturing of the tight inner circle of the royal family following the departure of Prince Harry, there are those who now dare to hope for an end to the monarchy. Opposition to monarchy in Britain is often perceived as a marginal belief that attracts few adherents. Traditionally the monarchy has proved adept at adapting to periods of change and crisis. Criticism of Queen Victoria’s long period of mourning and absence from public duties following the death of Prince Albert in 1861 led to a period of reappraisal that reshaped the appeal of the Crown. After her return to public life, Victoria changed the focus of the monarchy to make it more aligned with middle-class values, public philanthropy and charitable works. Thereafter, a ‘welfare monarchy’ entrenched the values of the royal house at the heart of civil society and proved key to the recovery and success of the public functions of the British Crown. The House of Windsor has followed that course since, most notably in Charles’ attempt to use his coronation to promote support for volunteering. The tradition of anti-monarchism, however, is as much a feature of British politics as monarchism, and is not, of itself, new. Issues of personal wealth, a narrow and privileged court, impersonal and unrepresentative royal influence and power, and the strong association between monarchy and the values of state, nation and empire have often inspired loathing. For some, like the radical Thomas Paine, hereditary rule was by its very nature immoral, privileging a politics ‘of the blood’ and institutionalising structures of ‘old corruption’ that drew courtiers, the civil service and the executive into an intertwined relationship rooted in power and position. Some monarchs, notably George IV, exemplified this trend and became emblematic of a remote and privileged court characterised by dysfunctional family and marital relations that evoked public scorn and derision. "
    },

    {
        title: "Archaeologists Discover 25 Mesolithic Pits in England",
        author: "Christopher Parker",
        profession: "Daily Correspondent at The Times",
        date: "2019-01-23",
        para: 'Archaeologists in Bedfordshire, England, have found a cluster of 25 monumental pits that date to the Mesolithic era, “a time with few clues to suggest what life was like in Britain,” according to a statement from the Museum of London Archaeology (MOLA).Researchers are calling the find “nationally significant,” saying that the site holds one of the largest collections of these kinds of pits ever found in Britain. “While we know of other large and enigmatic pits dug by hunter-gatherers from elsewhere in Britain, including at Stonehenge, the [Bedfordshire] pits are striking because of their number and the wide area they cover,” says Joshua Pollard, an archaeologist at England’s University of Southampton, in the statement. Each pit measures up to 5 meters (16 feet) wide and 1.85 meters (6 feet) deep. The researchers say that their creation would have required a lot of work, particularly because groups at this time were nomadic. The pits’ alignment—they’re situated in straight lines around former stream channels—could indicate that they had some sort of ritual significance. “People were going back to these pits over very, very long periods of time,” Pollard tells Roberto Perrone of BBC Three Counties Radio. “They became important points in the landscape that people returned to.” Inside the pits, the researchers unearthed the remains of wild animals, including aurochs—a species of wild cattle that humans may have eaten—deer, boar and the weasel-like marten. The team analyzed these bones using radiocarbon dating to determine that the pits are roughly 8,000 years old. An initial theory was that the pits functioned as traps, Pollard tells BBC Three Counties Radio. Researchers theorized that groups of hunters would corral animals into the pits to make them easier to kill. But upon further analysis, they concluded that the pits were likely used for spiritual celebrations. Pollard says the team is studying the alignment patterns to try to determine whether Mesolithic groups might have come to the pits for major celestial events.'
    },

    {
        title: "Medieval Manuscript Reveals 15th-Century Comedy Routine",
        author: "Natasha Geiling",
        profession: "",
        date: "2016-06-12",
        image: "https://th-thumbnailer.cdn-si-edu.com/pSYZEJd0Uf5PKASUdewuX7LgONg=/1000x750/filters:no_upscale():focal(400x301:401x302)/https://tf-cmsv2-smithsonianmag-media.s3.amazonaws.com/filer_public/ef/55/ef55e724-5a19-483f-b4ce-06757f2f9056/seamonster.jpg",
        para: 'If you’ve ever played the video game “Skyrim” or watched a Monty Python sketch, you’ve probably encountered medieval minstrels, performers who entertained audiences with stories, songs and stunts. But despite how often such characters appear in fiction, scholars know very little about what the average minstrel actually joked about. Now, a medieval comedy routine has been found in the pages of the Heege manuscript, a 15th-century text housed in the National Library of Scotland. “It gives us a glimpse into live comedy and entertainment in the Middle Ages that would otherwise be lost,” says James Wade, a literary scholar at the University of Cambridge, to the Washington Post’s Leo Sands. Wade is the author of a new study on the text published in The Review of English Studies. While the manuscript has been studied before, previous research focused primarily on its physical characteristics and significance as an artifact. The manuscript contains a wide range of comedic acts. One takes the form of a satirical sermon from a preacher, extolling the virtues of heavy drinking. Another is an “alliterative nonsense verse” titled “The Battle of Brackonwet.” The text also features the first known use of the term “red herring” in English. “A surprising conclusion is that medieval minstrels were offering comic performances, rather than the kinds of material we usually associate with medieval minstrelsy, such as Robin Hood ballads, tales of chivalry and accounts of great battles,” Wade tells Salon’s Matthew Rozsa. He was also impressed by the quality of the writing. “This minstrel is not only very funny, but also capable of performing good poetry and crafting clever and rhetorically sophisticated stories,” he adds. This discovery is quite rare, in part because such comedic acts were usually passed down through oral tradition. Wade writes that minstrels were often illiterate, and they might not have seen any financial benefit from preserving their acts in writing. Wade theorizes that this particular minstrel wrote down his act because it would have been especially difficult to recite by heart. “He didn’t give himself the kind of repetition or story trajectory which would have made things simpler to remember,” he says in a statement. The Heege manuscript, however, is not an original. Richard Heege was a tutor to a family in Derbyshire, and Wage says that he may have copied the text from a minstrel’s repertoire book.'
    }
]